##
# This file is part of the ChillDev-Commons.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2014 - 2016 Â© by Rafal Wrzeszcz - Wrzasq.pl.
##

#FIXME: https://github.com/travis-ci/travis-ci/issues/753

language: "java"

sudo: false

jdk:
    - "oraclejdk8"

install: true

script: "mvn verify site"

after_script: "mvn coveralls:report"

cache:
    directories:
        - "$HOME/.m2/"

before_cache:
    - "rm -rf $HOME/.m2/repository/pl/chilldev/commons"

notifications:
    webhooks:
        urls:
            - "https://webhooks.gitter.im/e/54252a58453d00b848db"
