##
# This file is part of the ChillDev-Commons.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2014 Â© by Rafal Wrzeszcz - Wrzasq.pl.
##

#FIXME: https://github.com/travis-ci/travis-ci/issues/753

language: "java"

jdk:
    - "openjdk7"
    - "oraclejdk7"
    - "oraclejdk8"

script: "mvn test verify"

after_script: "mvn site coveralls:cobertura"
